### ISSUE TITLE
linux `read` and `write` are not catched by radsan

### ISSUE THREAD

**Issue by maxmarsc** [realtime-sanitizer/radsan#28]
Both [read](https://man7.org/linux/man-pages/man2/read.2.html) and [write](https://man7.org/linux/man-pages/man2/write.2.html) operation seems not to be part of the interceptors.

Small example :
**radsan_test_.cpp**
```cpp
#include <cstdlib>

[[clang::realtime]] int main() {
  read(-1, nullptr, 0);
  write(-1, nullptr, 0);
  return 0;
}
```

```
$  /usr/local/radsan/bin/clang++ -fsanitize=realtime radsan_test.cpp -g -o radsan_test                               1 ↵
$ ./radsan_test    
```

**Comment by maxmarsc** [comment]
@davidtrevelyan Should we close this one as well as the merge mentions it ?

**Comment by cjappl** [comment]
Thanks for reminding us! Should be in there now :)

**Comment by davidtrevelyan** [comment]
So we don't actually have explicit interceptors for `read` and `write` yet. @cjappl did some good work to add them in, but unfortunately I was observing test failures on my local machine, so we had to revert the PR here: https://github.com/realtime-sanitizer/llvm-project/pull/17. I suspect that the fixes introduced in the latest radsan release may also fix the problems observed here. I'll try again adding `read` and `write` interceptors on top of our latest work, and see if the observed failures still happen, and I'll report back later this week!

**Comment by cjappl** [comment]
Whoops, good catch thanks!!

**Comment by cjappl** [comment]
Taking a quick peek -- I think it's a very real possibility that the "va_args" bug that caused #29 #31 and others were causing your test failures!

Specifically, in my PR I introduced this line:

https://github.com/realtime-sanitizer/llvm-project/pull/17/files#diff-a909e5293e90750218c151ed22637eee48f76738e9003f1235b0940a94c92064R233

```cpp

  void SetUp() override {
    fd = open(temporary_file_path(), O_RDWR | O_CREAT, S_IRUSR | S_IWUSR);
    ASSERT_TRUE(fd != -1) << "Failed to open file";
  }
```

Which as we know was the exact problematic version of open with 3 args that caused the aforementioned bugs! Damn, this is the bug that just keeps on giving 🐛

**Comment by cjappl** [comment]
Another great catch @maxmarsc - We have fixed this in the upstream and are unlikely to port it back
