### ISSUE TITLE
Incorrect file permission when using `open` with `-fsanitize=realtime`

### ISSUE THREAD

**Issue by DamRsn** [realtime-sanitizer/radsan#31]
Hi!

Thanks for creating radsan, I started using it yesterday and it already helped me spot a few real-time safety violations in my code!

However I had troubles setting it up because I think there's an issue in the `open` interceptor (and maybe in other filesystem interceptors). When a file is created, the file permissions are not the same whether you compile with radsan on or off (with or without`-fsanitize=realtime`). 

Here's a dummy example to reproduce the error. 

```
#include <fcntl.h>
#include <iostream>
#include <string>
#include <unistd.h>

int main()
{
    std::string filename = "test_radsan.txt";

    auto f = open(filename.c_str(), O_RDWR | O_CREAT, 00644);

    if (f == -1) {
        std::cerr << "Unable to open file!" << std::endl;
        return 1;
    }

    auto w = write(f, "Hello, World!", 13);

    if (w == -1) {
        std::cerr << "Error writing to file!" << std::endl;
        return 1;
    }

    // Close file
    auto c = close(f);

    if (c == -1) {
        std::cerr << "Error closing file!" << std::endl;
        return 1;
    }

    return 0;
}
```

With radsan off I get the expected:
<img width="373" alt="no_radsan" src="https://github.com/realtime-sanitizer/radsan/assets/56387835/aae8b240-fec6-4a7c-a8ae-0a8210c37fde">

But with radsan on (`-fsanitize=realtime`) I get this for debug:
<img width="370" alt="radsan_debug" src="https://github.com/realtime-sanitizer/radsan/assets/56387835/b7d20ea3-a329-4f70-9776-559175b9a84c">

and this for release:
<img width="375" alt="radsan_release" src="https://github.com/realtime-sanitizer/radsan/assets/56387835/324e2694-a2a5-4519-9016-7a19cfb08e06">

It seems that the `00644` argument in `open` may not be forwarded correctly in the interceptor. 

Also, commenting out all the filesystem interceptor in `radsan_interceptors.cpp` solves the permission issue. 

This issue might be related to #29. 

I'm on Mac (arm) with OSx 14.4.1. I built Radsan from source.

**Comment by davidtrevelyan** [comment]
Many thanks for the report @DamRsn - we can definitely take a look once upstreaming efforts have died down a bit :)

**Comment by davidtrevelyan** [comment]
PS: I think your observation of it being likely related to #29 is a good one - hopefully the fix for this will fix both!

**Comment by cjappl** [comment]
@DamRsn  think I have a fix for this! Would you pull down the small change in this PR and give it a go? It works both in unit testing and using your binary for me.

Thanks for reporting this, we would have had no idea otherwise. Sincerely appreciate the help.

**Comment by DamRsn** [comment]
Hi,

I just tried the fix and it works with the simple example I provided. 

However when I use it in my bigger project (where I first detected the issue), it's still not working and I'm getting errors when I try to open my database file with [sqlite_orm](https://github.com/fnc12/sqlite_orm). 

When I comment out the file interceptors, it works as expected, so it seems that the intercepted filesystem calls are not behaving exactly as their REAL equivalent. 

Sorry, I don't any more specific information at the moment, I tried to go as deep as possible with the debugger in `sqlite_orm` but I could not get down to the `open` or `read` calls where the error must be occurring. I don't know if it is still permission issue or not.

**Comment by DamRsn** [comment]
Here's the list of interceptors that I commented out (both their definition and in `initialiseInterceptors()`.

open
openat
close
fopen
fread
fwrite
fclose
fcntl
creat
puts
fputs

I'll try do narrow it down with bissection, but right now I have some issue buildingmy project with different compiler versions and RadSAN so I'll fix that first.

**Comment by cjappl** [comment]
I just pushed another change to that branch, fixing the same problem in fcntl. Before bisecting, check that out and see if it helps.

**Comment by davidtrevelyan** [comment]
@DamRsn we've just pushed out a new release to the `main` branch and to the Docker registry. Let us know if this fixes your issue :)

**Comment by DamRsn** [comment]
I've built of radsan main branch and everything seems to work well now. I don't need to comment the file interceptor anymore.

Thanks a lot for fixing this!

**Comment by cjappl** [comment]
Thanks to you for reporting this!! This ended up being 3-4 different issues that we couldn't figure out until you put your easy-to-repro example.

Sincerely appreciate your report, glad you're unblocked
