### ISSUE TITLE
CMake missing in docker image

### ISSUE THREAD

**Issue by cjappl** [realtime-sanitizer/radsan#6]
Trying out the Docker image for the first time and noticing there is no cmake binary in the image. When we rebuild and repost, it may be nice to have it included.

My test project that I've been using on OSX was a simple CMake project (as is typical these days, I think) and I had to dig through it to find the compiler commands to test the docker container version.

**Comment by davidtrevelyan** [comment]
Hmmm, yes - that was a deliberate choice at the time, in an effort to keep the image size as small as possible and act as a base image (expecting people to install, for example, whatever version of CMake they need, along with any other dev tools and dependencies). Even though it's straightforward to do this, I do appreciate what you say - CMake is pretty standard these days, and it's fairly small, so it could be a helpful addition. I'm unsure where to draw the line on this one!

**Comment by cjappl** [comment]
Ah, I think that that is a good idea! 

Forgive me, as my Docker knowledge is basically 0. Is this what you meant by this section of the README?

```
FROM realtimesanitizer/radsan-clang:latest
RUN apt-get update && apt-get install -y git cmake vim
```

I think this can likely be closed, I like the idea of keeping the image as small as humanly possible. Thanks for the help/explanation

**Comment by davidtrevelyan** [comment]
No probs! Yes, that correct - that's what I mean by that Dockerfile snippet in the README 👍
