### ISSUE TITLE
radsan_on and  _off will not work without including radan.h and using -fsanitize=realtime

### ISSUE THREAD

**Issue by cjappl** [realtime-sanitizer/radsan#7]
In the README it mentions you can surround a false positive with radsan_on and radsan_off, simply by including a header

Because these are compiled calls, the user will have to link some library to get this to work, which is invasive.

There are two problems: 

1. [INCORRECT, see edit] The readme is missing info about this library so that example will not work
2. This suppression mechanism is invasive and involves more friction than other sanitizer suppression mechanisms.

It would be nice to be able to suppress with an attribute (supported by tsan, asan) or a suppression list (asan) that allow suppression while not needing to be linked in.

EDIT:
Because rtsan is linked in by using the -fsanitize flag, these calls WILL run when you link it in. However, this leads us to the next problem. You must have this header around, and link with -fsanitize=realtime.

I could see some solution like:

```
#if SANITIZING_WITH_RADSAN
extern void radsan_on();
extern void radsan_off();
#else    
void radsan_on() {};
void radsan_off(){};
#endif 
```

But kind of invasive still, as every project needs to define some block like this

**Comment by davidtrevelyan** [comment]
Yeah, this is a tough one. It's tough because in this specific sanitizer, the choice to suppress an interception depends not just on the function being intercepted, but also where the function is called. Consider `pthread_mutex_lock` - maybe the user wants to suppress interception for one particular mutex they know is never contended during real-time use - they don't want to suppress _all_ interceptions of `pthread_mutex_lock`, because they might miss a lock around a large `atomic`, for example. A simple suppression list wouldn't do what they need here.

I haven't looked into suppressing with an attribute yet - could you point me to a good example? 

So - I agree the README needs more info. Let's nail down exactly what we want the user to do in this case before changing it, though. I'm not sure there's a way to avoid the requirement of linking to the RADSan library in order to suppress at run time - did you have any ideas for this already?

**Comment by cjappl** [comment]
> Yeah, this is a tough one. It's tough because in this specific sanitizer, the choice to suppress an interception depends not just on the function being intercepted, but also where the function is called. Consider pthread_mutex_lock - maybe the user wants to suppress interception for one particular mutex they know is never contended during real-time use - they don't want to suppress all interceptions of pthread_mutex_lock

That's an excellent point, that does make this tricky...

> I haven't looked into suppressing with an attribute yet - could you point me to a good example?

1. asan suppression with attribute

https://stackoverflow.com/a/33352208

2. Threadsan suppression file

https://github.com/google/sanitizers/wiki/ThreadSanitizerSuppressions


I think these could possibly work for RADSan, imagine the example from the README:

```
#include "radsan.h" // (found in llvm-project/compiler-rt/lib/radsan)

[[clang::realtime]] float process (float x)
{
    auto const y = 2.0f * x;

    radsan_off();
    i_know_this_method_is_realtime_safe_but_radsan_complains_about_it();
    radsan_on();
}
```


Instead, the user would decorate that specific method:

```
[[clang::realtime]] float process (float x)
{
    auto const y = 2.0f * x;

    i_know_this_method_is_realtime_safe_but_radsan_complains_about_it();
}

__attribute__((no_sanitize("realtime")))
void i_know_this_method_is_realtime_safe_but_radsan_complains_about_it()
{
   ...
}

```

This also has a "self documenting" kind of flair about it, in that it shows to any future readers that we know this thing is not realtime safe, but it can be used in process loops.


For the example of a mutex, you could have an additional method you use that adds a little boilerplate, but again also self documents:


```
[[clang::realtime]] float process (float x)
{
    realtime_lock(my_mutex);

    auto const y = 2.0f * x;

   realtime_unlock(my_mutex);
}

__attribute__((no_sanitize("realtime")))
void realtime_lock(std::mutex& m)
{
   m.lock()
}

```

(or have a realtime_scoped_lock that puts the attribute on the constructor/destructor)

**Comment by cjappl** [comment]
This is possible, and I have a (extremely, extremely rough) version of it here:

https://github.com/realtime-sanitizer/llvm-project/pull/6

I need to sleep on it a bit and see if there are any cleaner ways to do it without introducing another attribute. Maybe this is more clear to the two original maintainers who have been in this code longer.

**Comment by cjappl** [comment]
@davidtrevelyan to follow up on our conversation, having some problems declaring `radsan_on` and `radsan_off` as extern:

(truncated, compiling with `-fsanitize=realtime`
```
#include "/Users/topher/code/radsan_cjappl/llvm-project/compiler-rt/lib/radsan/radsan.h"

void* realtime_safe_malloc_part_two (size_t size)
{
    radsan_off();
    auto* x = malloc (size);
    radsan_on();

    return x;
}
```

Works as intended, compiles and runs.

```
extern void radsan_on();
extern void radsan_off();

void* realtime_safe_malloc_part_two (size_t size)
{
    radsan_off();
    auto* x = malloc (size);
    radsan_on();

    return x;
}

```

Does not link, error:

```
[100%] Linking CXX executable MyExecutable
ld: Undefined symbols:
  radsan_off(), referenced from:
      realtime_safe_malloc_part_two(unsigned long) in main.cpp.o
  radsan_on(), referenced from:
      realtime_safe_malloc_part_two(unsigned long) in main.cpp.o
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Am I missing something obvious? I haven't dealt too heavily with externally defined/linked functions before, I could be missing something obvious.

**Comment by cjappl** [comment]
(updated the description to be more accurate)

**Comment by davidtrevelyan** [comment]
@cjappl You're missing something small, but it's not obvious. Those RADSan methods are declared as `extern "C"` in the radsan header, not just `extern`. `extern "C"` tells the compiler not to mangle the function names with extra information about the arguments, like C++ does normally. This enables C projects (which don't expect name mangling) to also use RADSan if they want (although we forgot to protect the declaration in the header with an `#ifdef __cplusplus`! Oops. I'll make that fix today!).

If I've understood the problem correctly, it looks to me like that linker error you're getting has "helpfully" demangled the symbol names that it's really searching for, but in this case it's actually hidden the problem! If I've misunderstood the problem, I can help look further into this :)
