### ISSUE TITLE
One of the tests leaves a file.txt without cleaning it up

### ISSUE THREAD

**Issue by cjappl** [realtime-sanitizer/radsan#9]
Not sure which one yet, but if you use the proposed new makefile:

```
> git status
On branch Workflow
Your branch is up to date with 'origin/Workflow'.

nothing to commit, working tree clean
> make test
...
> git status
On branch Workflow
Your branch is up to date with 'origin/Workflow'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        file.txt

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by davidtrevelyan** [comment]
Oops, thanks! Should be a super easy fix. I can take a look first thing tomorrow.

**Comment by davidtrevelyan** [comment]
@cjappl PR ready for your review [here](https://github.com/realtime-sanitizer/llvm-project/pull/7) - once it's in I'll update the fork in this parent repo 👍

**Comment by davidtrevelyan** [comment]
The fix was merged in https://github.com/realtime-sanitizer/llvm-project/pull/7, but the fork submodule has not yet been updated - I think we're waiting for a handful of fixes to go in before updating. I'll leave this issue open until the fork is updated :)

**Comment by cjappl** [comment]
Confirmed fixed on my machine 👍
